### ISSUE TITLE
Adjust ansible galaxy to import the collection from the nextcloud namespace

### ISSUE THREAD

**Issue by aalaesar** [nextcloud/ansible-collection-nextcloud-admin#186]
Check how to add/move the collections to the new namespace into galaxy (trying to keep stats) 
- [x] https://galaxy.ansible.com/docs/contributing/namespaces.html

**Comment by aalaesar** [comment]
Hello there.
I've spent some more brain juice on this subject And for now I don't think ansible have any workflow that would allow  to change the role into the target collection. :disappointed: 

But for now the nextcloud namespace must be created in galaxy.
Reviewing again [galaxy's doc](https://galaxy.ansible.com/docs/contributing/namespaces.html),
unlike I assumed, having the proper rigths in a github organization is not enough to create the proper namespace automatically. In fact, [it's a manual process ](https://galaxy.ansible.com/docs/contributing/namespaces.html#requesting-additional-namespaces).

@AndyScherzinger 
Maybe an admin of the organization should [do the request](https://github.com/ansible/galaxy/issues/new?template=New_namespace.md), or could I ?

**Comment by aalaesar** [comment]
After creating the namespace, [publishing the collection](https://docs.ansible.com/ansible/devel/dev_guide/developing_collections_distributing.html#publishing-a-collection-from-the-command-line) will requires some adjustment of [the release workflow](https://github.com/nextcloud/ansible-collection-nextcloud-admin/blob/main/.github/workflows/release.yml#L47)

**Comment by staticdev** [comment]
> After creating the namespace, [publishing the collection](https://docs.ansible.com/ansible/devel/dev_guide/developing_collections_distributing.html#publishing-a-collection-from-the-command-line) will requires some adjustment of [the release workflow](https://github.com/nextcloud/ansible-collection-nextcloud-admin/blob/main/.github/workflows/release.yml#L47)

I can PR it soon.

**Comment by aalaesar** [comment]
Hello there.

friendly reminder to nextcloud admins (@AndyScherzinger , @jospoortvliet).
Do you wish to request the creation of the nextcloud namespace in ansible galaxy or you are allowing us (me or the maintainers of this repo) to do it for you ?

This is a one time mandatory action to do that'll allow the collection to be release.

> @AndyScherzinger Maybe an admin of the organization should [do the request](https://github.com/ansible/galaxy/issues/new?template=New_namespace.md), or could I ?

**Comment by AndyScherzinger** [comment]
I'd be fine with you doing it.

For the additional administrators part, please add at least me, can't say if @blizzz and @mgallien also logged into galaxy.ansible.com at least once (I at least have)

**Comment by aalaesar** [comment]
request sent: https://github.com/ansible/galaxy/issues/3122

**Comment by aalaesar** [comment]
done with namespace created and PR merged
