### ISSUE TITLE
Support Debian 12

### ISSUE THREAD

**Issue by staticdev** [nextcloud/ansible-collection-nextcloud-admin#213]
It is coming, let's get ready =)

**Comment by aalaesar** [comment]
Hello there !

I've just checked the php suported version . and it's only 7.4.
I'm a bit disappointed  that's not 8.0 or more, but at least it won't change how the role have to manage php for this one.

I don't have in mind some task that would obviously break with it.
So, except of updating the CI and adding a test for it, do you have some part in mind that would requires attention ?

Regards.

**Comment by wiktor2200** [comment]
Hi! Good idea to have this task to track progress :) 

It's very disappointing that they won't include php8.0 into final version. What is more php 7.4 is already EOL (and 8.0 will be Q3 2023), so it's more than weird decision. :(
https://www.php.net/supported-versions.php

They've got "hard freeze" on 12nd of March, so we would see then.

**Comment by staticdev** [comment]
Where did you get this info? 
Bookworm already has 8.2.2:
https://packages.debian.org/bookworm/php

**Comment by aalaesar** [comment]
> Where did you get this info? Bookworm already has 8.2.2: https://packages.debian.org/bookworm/php

Hm I looked at https://www.debian.org/releases/testing/amd64/release-notes/ch-whats-new.fr.html#major-packages
Although the document stated that is was not guaranteed. I was not expecting such a delta

My bad :)

**Comment by staticdev** [comment]
Actually I think bookwork will require not yet released NC 26.
