### ISSUE TITLE
Change default GITHUB_TOKEN to generated personal access token for dependabot.

### ISSUE THREAD

**Issue by wiktor2200** [nextcloud/ansible-collection-nextcloud-admin#234]
Hi @aalaesar, @staticdev!
We need to change default token to custom in pre-commit update here:
https://github.com/nextcloud/ansible-collection-nextcloud-admin/blob/5286bef6116da18a3521c9b8b966b51aec5e6dab/.github/workflows/precommit-update.yml#L23

I don't have sufficient permissions to generate new token for `dependabot[bot]` user. @aalaesar Could you create new token and call it for example: `GITHUB_TOKEN_DEPENDABOT` or `GITHUB_TOKEN_PRECOMMIT_UPDATE`? I'll change above line then.

Longer story with whole problem explained is covered here: https://github.com/peter-evans/create-pull-request/issues/1715

**Comment by staticdev** [comment]
@wiktor2200 I also dont have permission, I already reverted your previous PR

**Comment by aalaesar** [comment]
Ok so I created the Token TOKEN_DEPENDABOT (can't prefix secrets with github) and now the CI commit will be authored by "me" if I'm understanding it correctly.

**Comment by wiktor2200** [comment]
Hi @aalaesar!
Is this token **your** personal token? Or repository specific one?
I think, it's not a good idea if it's yours and we should probably leave it as it is with default `github-action`, when `dependabot` user is not possible here.

The main problem was to differentiate dependencies updated by `dependabot` and having all actions (`yamllint` and `ansible-lint`) run within pre-commit update PR.

But if it's not possible I think we should drop it for know. Versions update are not a big deal and should not break `yamlint` or `ansible-lint` results (especially for pre-commit).

WDYT? @aalaesar @staticdev

**Comment by aalaesar** [comment]
> Hi @aalaesar! Is this token **your** personal token? Or repository specific one? I think, it's not a good idea if it's yours and we should probably leave it as it is with default `github-action`, when `dependabot` user is not possible here.

Yes, It's _just a_ personal acces token , as specified by the action's author. With just enough scope to make the action working.


> But if it's not possible I think we should drop it for know. Versions update are not a big deal and should not break `yamlint` or `ansible-lint` results (especially for pre-commit).
> 
> WDYT? @aalaesar @staticdev
 Could be _nice_ to get matching versions for precommits and tests in ci. But why needing absolutely the ci to trigger linters for those commits ?
 I think the pre-commit  config may be ignored by the linters anyway.

**Comment by wiktor2200** [comment]
> Yes, It's _just a_ personal acces token , as specified by the action's author. With just enough scope to make the action working.

It thought it would be possible to generate PAT for dependabot[bot] but it seems not to be possible.



> Could be _nice_ to get matching versions for precommits and tests in ci. But why needing absolutely the ci to trigger linters for those commits ?

pre-commits updates works and are commited by dependabot: https://github.com/nextcloud/ansible-collection-nextcloud-admin/pull/231/commits
All versions should be the same in: pre-commit, test and dependencies in role/python modules, because both pre-commit update and dependabot run once a day on schedule :)



> I think the pre-commit config may be ignored by the linters anyway.

I think it's a best idea to ignore it, as it's bigger work than I expected and probably not worth the effort.

**Comment by staticdev** [comment]
@wiktor2200 i have seen cases when pre-commit updates of yamllint or ansible-link breaks the repo. This can happen when new checks are added or severity of a check is increased.

**Comment by wiktor2200** [comment]
Hmmm.. so I see two possible solutions:
1. Use @aalaesar's TOKEN to trigger pipeline (so yamllint and ansible-lint) should be run. - That's what I don't really like and I think it's better not to use his PAT :)
2. I can modify pre-commit update job and add duplicated code for ansible-lint and yamlint here: https://github.com/nextcloud/ansible-collection-nextcloud-admin/blob/93dd139ed1ad832b09d116c0e6d260dcef0b8f69/.github/workflows/precommit-update.yml#L20
between `browniebroke/pre-commit-autoupdate-action@main` and `peter-evans/create-pull-request@v4` so in this case PR shouldn't be created when linters will fail.

What do you think?

**Comment by wiktor2200** [comment]
Here you can see changes mentioned above in Ad. 2: 
https://github.com/wiktor2200/ansible-collection-nextcloud-admin/blob/38207a5574b98422942f64a389e87b5cff632b99/.github/workflows/precommit-update.yml#L20

If you agree for this solution I'll create PR :)

**Comment by wiktor2200** [comment]
@staticdev What do you think about it?

**Comment by aalaesar** [comment]
Fine for me

**Comment by wiktor2200** [comment]
As adding additional step to pre-commit update failed and I still doesn't want to use your personal token @aalaesar. I would propose adding schedule to ansible-yaml and yamllint (to be run daily). So we would find possible linter problems if pre-commit update will mess something up.
What do you think about it?

**Comment by wiktor2200** [comment]
Hi! Changes to scheduled jobs were introduced in #245 anyway, so my proposal from last message is no longer valid. I'm closing this issue.
