### ISSUE TITLE
Update web servers X-Robots-Tag header

### ISSUE THREAD

**Issue by wiktor2200** [nextcloud/ansible-collection-nextcloud-admin#246]
After upgrading to `25.0.5` or 26 major version, there are warnings about header.
More information could be found here: 
* https://github.com/nextcloud/server/pull/36689 
* https://help.nextcloud.com/t/x-robots-tag-http-header-not-configured-with-noindex-nofollow-since-nc-26-0-0/158300

There are some more upcoming changes in web server config in 26, so this task is connected with #241 and should be done accordingly.

**Comment by aalaesar** [comment]
Hello there !
Thank you for the report @wiktor2200 
It seems this update can be applied for all versions. So I suppose updating the templates is enough 

Ps I also noted in the same discussion  the remark about nginx caching for images. I'll check that.

**Comment by wiktor2200** [comment]
Hi!
Yes, mentioned X-Robots was only one of the changes. I'm going to look through new nginx/apache2 documentation and will 
follow-up our jinja template.
