### ISSUE TITLE
install_nextcloud : unable to locate collection ansible.utils

### ISSUE THREAD

**Issue by Kaor** [nextcloud/ansible-collection-nextcloud-admin#249]
Hi,
thank you for your work,
i use install_nextcloud on fresh debian 11 (apt install ansible) on LXC container
`fatal: [localhost]: FAILED! => {"changed": false, "msg": "AnsibleError: template error while templating string: unable to locate collection ansible.utils. 
...
`
i install ansible.utils and it's ok 
`ansible-galaxy collection install ansible.utils`

**Comment by wiktor2200** [comment]
Hi Kaor! Thanks for your feedback, `ansible.utils` collection is needed to manage: `nextcloud_trusted_domain` variable which is used in both Apache2 and Nginx configurations.

I've just created PR for that: #251
