### ISSUE TITLE
Add link to galaxy on github description of the repo

### ISSUE THREAD

**Issue by staticdev** [nextcloud/ansible-collection-nextcloud-admin#267]
I usually add a link to galaxy in the description in GH. It makes it handy to navigate back and forth from GH and Galaxy.

![image](https://user-images.githubusercontent.com/1446633/235203644-c8ffc99f-a1ea-4db9-9ba7-a5234558b79a.png)

@aalaesar could you add the link to the collection on description of the repository? https://galaxy.ansible.com/nextcloud/admin

**Comment by aalaesar** [comment]
Done. Thank you for the suggestion
