### ISSUE TITLE
I suggest to rename the role "install_nextcloud" to "install" only

### ISSUE THREAD

**Issue by marioqxx** [nextcloud/ansible-collection-nextcloud-admin#274]
Now that the collection includes a "backup"-role, for consistency reasons it would seem more mogic to renamte the "install_nextcloud"-role to "install" only.

**Comment by wiktor2200** [comment]
Hi @marioqxx! Thanks for your suggersion, it's a good idea
We also noticed that and already started discussion #228 few months ago. I'm closing this issue, as we're storing ideas in `Discussions` tab.
