### ISSUE TITLE
yamllint GA abandoned not working since last year

### ISSUE THREAD

**Issue by staticdev** [nextcloud/ansible-collection-nextcloud-admin#284]
The pipeline is failing every execution. I suggest we create replace the action and have single lint workflow with yamllint and ansible-lint as in:

https://github.com/staticdev/ansible-role-signal/blob/main/.github/workflows/tests.yml#LL16C1-L37C23

**Comment by aalaesar** [comment]
Hello there !

> The pipeline is failing every execution. 

can you elaborate ? A quick check shows everything looks ok .

> I suggest we create replace the action and have single lint workflow with yamllint and ansible-lint

OK as ansible lint test comes already with ansible-lint For what I'm seeing.

regards

**Comment by staticdev** [comment]
@aalaesar just check here https://github.com/nextcloud/ansible-collection-nextcloud-admin/actions

**Comment by wiktor2200** [comment]
Hi! Sorry for late response. Yeah it's a good idea to fix that. I've already reviewed these changes.
