### ISSUE TITLE
open_basedir set inside config.php

### ISSUE THREAD

**Issue by cm-schl** [nextcloud/ansible-collection-nextcloud-admin#302]
Hi,

looking at the resulting `config.php` there is set a line `'open_basedir' => '/dev/urandom'`.

https://github.com/nextcloud/ansible-collection-nextcloud-admin/blob/40710864b8336cbc6884bfb39b02e29de2146bab/roles/install_nextcloud/defaults/main.yml#L77

I can't find anything on this in the Nextcloud documentation for configuration parameters and "normally" this is set inside the `php.ini`.

Can the open_basedir really be set inside the `config.php`?

**Comment by staticdev** [comment]
Fair point.. it seems not.
