### ISSUE TITLE
Install on Ubuntu Server 23.10 fails due to a bug in ubuntu

### ISSUE THREAD

**Issue by marioqxx** [nextcloud/ansible-collection-nextcloud-admin#312]
This is not a bug of this ansible script, which fails due to a confirmed bug in ubuntu, See https://bugs.launchpad.net/ubuntu/+source/php-apcu/+bug/2038916. 

I leave this here for information purposes only until this bug in ubuntu server 23.10 is resolved.

**Comment by staticdev** [comment]
@marioqxx amyway there is no intention to support this version. We support only LTS versions.

**Comment by marioqxx** [comment]
Thats fine, 24.04 is out anyway soon.
