### ISSUE TITLE
PHP message: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted

### ISSUE THREAD

**Issue by staticdev** [nextcloud/ansible-collection-nextcloud-admin#322]
134217728 corresponds roughly to 128mb, in fact this is the default `memory_limit` for `fpm`. Our installed just sets `memory_limit` for apache `php.ini` but not to `fpm` which is independent.

**Comment by aalaesar** [comment]
Hello there !
By curiosity, does that happen for the php cronjob or for the some command of the occ cli ?

**Comment by staticdev** [comment]
Hello @aalaesar. This happened to me during an upgrade.
